# Generated by Django 5.2.1 on 2026-05-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_savedroute_end_latitude_savedroute_end_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedroute',
            name='route_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='savedroute',
            name='route_duration_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedroute',
            name='route_geometry',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
