# Generated by Django 5.2.1 on 2026-05-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_savedroute_route_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedroute',
            name='main_road_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='savedroute',
            name='main_road_duration_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedroute',
            name='main_road_geometry',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedroute',
            name='selected_route_type',
            field=models.CharField(choices=[('shortcut_lane', 'Shortcut Lane'), ('main_road', 'Main Road')], default='main_road', max_length=32),
        ),
        migrations.AddField(
            model_name='savedroute',
            name='shortcut_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='savedroute',
            name='shortcut_duration_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedroute',
            name='shortcut_geometry',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
