# Generated by Django 5.2.1 on 2026-05-21 06:16

import django.core.validators
import django.db.models.deletion
import reports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('dark_area', 'Dark Area'), ('broken_street_light', 'Broken Street Light'), ('flooded_road', 'Flooded Road'), ('stray_dogs', 'Stray Dogs'), ('accident_prone_area', 'Accident-Prone Area'), ('suspicious_activity', 'Suspicious Activity'), ('broken_sidewalk', 'Broken Sidewalk'), ('unsafe_shortcut', 'Unsafe Shortcut'), ('harassment_concern', 'Harassment Concern'), ('poor_visibility', 'Poor Visibility'), ('no_pedestrian_lane', 'No Pedestrian Lane'), ('other', 'Other')], max_length=40)),
                ('description', models.TextField(max_length=2000)),
                ('location_name', models.CharField(max_length=160)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('needs_admin_review', 'Needs Admin Review')], default='pending', max_length=32)),
                ('time_observed', models.TimeField(default=reports.models.current_local_time)),
                ('day_type', models.CharField(choices=[('weekday', 'Weekday'), ('weekend', 'Weekend')], default='weekday', max_length=16)),
                ('lighting_condition', models.CharField(choices=[('bright', 'Bright'), ('moderate', 'Moderate'), ('dim', 'Dim'), ('no_light', 'No Light')], default='moderate', max_length=20)),
                ('crowd_level', models.CharField(choices=[('crowded', 'Crowded'), ('moderate', 'Moderate'), ('few_people', 'Few People'), ('empty', 'Empty')], default='moderate', max_length=20)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('visibility_level', models.CharField(choices=[('public', 'Public'), ('anonymous_public', 'Anonymous Public'), ('admin_only', 'Admin Only')], default='public', max_length=24)),
                ('image_url', models.URLField(blank=True)),
                ('safety_score', models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('evidence_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('credibility_label', models.CharField(choices=[('unverified', 'Unverified'), ('community_supported', 'Community Supported'), ('strong_evidence', 'Strong Evidence'), ('admin_verified', 'Admin Verified')], default='unverified', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('needs_admin_review', 'Needs Admin Review')], max_length=32)),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('needs_admin_review', 'Needs Admin Review')], max_length=32)),
                ('admin_note', models.CharField(blank=True, max_length=700)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_status_updates', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='reports.safetyreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_type', models.CharField(choices=[('confirmed', 'Confirmed'), ('disputed', 'Disputed'), ('resolved_by_community', 'Resolved by Community'), ('needs_review', 'Needs Review')], max_length=32)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_confirmations', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='reports.safetyreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='safetyreport',
            index=models.Index(fields=['location_name'], name='reports_saf_locatio_ac844d_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyreport',
            index=models.Index(fields=['category', 'risk_level'], name='reports_saf_categor_b9d54f_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyreport',
            index=models.Index(fields=['status'], name='reports_saf_status_586e78_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportconfirmation',
            constraint=models.UniqueConstraint(fields=('report', 'user'), name='unique_confirmation_per_user_report'),
        ),
    ]
