# Generated by Django 5.2.1 on 2026-05-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetyreport',
            name='image_url',
        ),
        migrations.AddField(
            model_name='safetyreport',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='report_photos/'),
        ),
    ]
