# Generated by Django 5.2.1 on 2026-05-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_safetyreport_image_url_safetyreport_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetyreport',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='report_photos/'),
        ),
    ]
