# Generated by Django 5.2.1 on 2026-05-22 14:21

from django.db import migrations, models


def convert_admin_review_values(apps, schema_editor):
    SafetyReport = apps.get_model("reports", "SafetyReport")
    ReportStatusHistory = apps.get_model("reports", "ReportStatusHistory")
    ReportConfirmation = apps.get_model("reports", "ReportConfirmation")

    SafetyReport.objects.filter(status="needs_admin_review").update(status="pending")
    ReportStatusHistory.objects.filter(old_status="needs_admin_review").update(old_status="pending")
    ReportStatusHistory.objects.filter(new_status="needs_admin_review").update(new_status="pending")
    ReportConfirmation.objects.filter(confirmation_type="needs_review").update(confirmation_type="comment")


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_safetyreport_photo'),
    ]

    operations = [
        migrations.RunPython(convert_admin_review_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='reportconfirmation',
            name='confirmation_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('confirmed', 'Confirmed'), ('disputed', 'Disputed'), ('resolved_by_community', 'Resolved by Community')], max_length=32),
        ),
        migrations.AlterField(
            model_name='reportstatushistory',
            name='new_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], max_length=32),
        ),
        migrations.AlterField(
            model_name='reportstatushistory',
            name='old_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], max_length=32),
        ),
        migrations.AlterField(
            model_name='safetyreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=32),
        ),
    ]
