# Generated by Django 5.2.1 on 2026-05-22 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_reportconfirmation_confirmation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyreport',
            name='credibility_score',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='reportconfirmation',
            name='confirmation_type',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('disputed', 'Disputed'), ('resolved_by_community', 'Resolved by Community'), ('needs_more_evidence', 'Needs More Evidence'), ('comment', 'Comment')], max_length=32),
        ),
        migrations.AlterField(
            model_name='safetyreport',
            name='credibility_label',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('community_supported', 'Community Supported'), ('strong_evidence', 'Strong Evidence'), ('highly_credible', 'Highly Credible'), ('admin_verified', 'Admin Verified'), ('rejected_not_credible', 'Rejected / Not Credible')], default='unverified', max_length=32),
        ),
    ]
